# Generated by Django 5.2.12 on 2026-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpermissionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Name user prefers to be called by AI assistant', max_length=100, null=True),
        ),
    ]
