# Generated by Django 5.2.12 on 2026-04-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('view_all_projects', 'Can view all projects')]},
        ),
    ]
