# Generated by Django 5.2.12 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('PDF', 'PDF'), ('IMAGE', 'Image'), ('LINK', 'Link')], max_length=10, null=True),
        ),
    ]
