# Generated by Django 6.0.2 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='project_resources/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='resource_link',
            field=models.URLField(blank=True, help_text='Reference URL', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='resource_text',
            field=models.TextField(blank=True, help_text='Notes or reference text', null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
