# Generated by Django 5.2.12 on 2026-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectresource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
