# Generated by Django 6.0.2 on 2026-03-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projects_resource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('FILE', 'file'), ('LINK', 'link'), ('TEXT', 'text')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_resources/')),
                ('link', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectResouce',
        ),
    ]
