# Generated by Django 6.0.2 on 2026-03-05 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectresource_delete_projectresouce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='projects',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
