# Generated by Django 6.0.2 on 2026-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projects_assigned_to_projects_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectresource',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectresource',
            old_name='text',
            new_name='text_content',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PDF', 'PDF'), ('IMAGE', 'Image'), ('LINK', 'Link')], max_length=10),
        ),
    ]
