# Generated by Django 5.2.12 on 2026-04-07 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_content_messageattachment'),
        ('projects', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='projects.projects'),
        ),
    ]
