# Generated by Django 5.2.12 on 2026-03-24 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['ADMIN', 'TEAM_LEAD']}, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
