# Generated by Django 5.2.12 on 2026-04-01 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_task_assigned_by_task_assigned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ManyToManyField(related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
