# Generated by Django 5.2.12 on 2026-04-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_assigned_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('view_all_tasks', 'Can view all tasks')]},
        ),
    ]
