# Generated by Django 6.0.3 on 2026-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_task_assigned_by_task_created_at_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
