# Generated by Django 6.0.3 on 2026-03-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_task_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(default=3600, help_text='Estimated time in seconds'),
        ),
    ]
